```{r}
df <- read_excel("df2.xlsx")

df$ind = as.factor(df$ind)
names(df)[names(df) == "Platô"] = "plato"

df$ideal = ifelse(df$ideal == 'ideal', 1, 0)
#df$ideal = as.factor(df$ideal)
#df$ideal %>% levels()
df$ideal %>% class()

df_backup = df
```


```{r}

col_analise = 'Pico'
col_analise = 'plato'
col_analise = 'Driving'

ggplot(df, aes(x= as.numeric(PEEP), y= !!sym(col_analise), color= ind)) + 
  geom_line(aes(group= ind)) + 
  facet_grid(Momento~.) + 
  theme_bw() + theme(legend.position = 'none') +
  scale_x_continuous(breaks=seq(from=0, to=100, by=1)) +
  scale_y_continuous(breaks=seq(from=0, to=100, by=1))

#ggsave(paste0(col_analise,".png"), height=25, width=20, units="cm", dpi=600)

```


```{r}

for (letra in c('A','B','C')){
  coluna_x = 'ideal'
  coluna_y = 'PEEP'
  
  p0 = conti(df %>% filter(Momento == letra), 'ideal', 'PEEP', sentido_percent = 'row')
  print(p0)
  p = conti_grafi(df %>% filter(Momento == letra), 'ideal', 'PEEP') +
    labs(x='PEEP', fill=NULL) + scale_fill_grey()
  print(p)
  ggsave("nome_grafico.png", height=15, width=20, units="cm", dpi= 600)
}
```
```{r}

for (letra in c('A','B','C')){
  coluna_x = 'ideal'
  coluna_y = 'PEEP'
  
  grafi = df %>% filter(!is.na(!!sym(coluna_x)) & !is.na(!!sym(coluna_y))) %>% filter(Momento == letra) %>% 
      group_by(!!sym(coluna_y), !!sym(coluna_x)) %>% 
      summarise(n = n()) %>% mutate(Freq = round(n/sum(n)*100, 2)) %>% ungroup()
  grafi = grafi %>% filter(ideal == 1)
  
  p = ggplot(grafi, aes(x=as.factor(!!sym(coluna_y)), y=Freq, label=Freq, fill=as.factor(!!sym(coluna_y)))) + 
    # Grafico
    geom_col(show.legend=FALSE, color="black") + 
    # Outros
    geom_text(aes(y=Freq, label = sprintf("%0.1f%%", Freq), vjust=-0.1)) + 
    theme_bw() + theme(legend.position = "bottom") +
    scale_y_continuous(limits = c(0, 100), breaks=seq(from = 0, to = 100, by = 20)) +
    labs(x=NULL, y="Frequency (%)", title =NULL) +
    scale_fill_grey()
  print(p)
}

```
```{r}
dff = df %>% filter(Momento == 'C') %>% mutate(PEEP = as.factor(PEEP))
```


```{r Modelo GEE}
library(geepack)
modelo_gee <- geeglm(ideal ~ as.factor(PEEP), id = ind, data = dff, family = binomial, corstr = "exchangeable")
modelo_gee %>% summary()

# Previsões para o modelo GEE
pred_gee <- predict(modelo_gee, type = "response")
# Converter previsões em binário
class_pred_gee <- ifelse(pred_gee > 0.5, 1, 0)
```

```{r MODELO GLME}
library(lme4)

#modelo_lme = glmer(ideal ~ as.factor(PEEP) + (1 | ind), data = dff, family = binomial)
#modelo_lme %>% summary()

modelo_lme <- glmer(ideal ~ as.factor(PEEP) + (1 | ind), 
                    data = dff, family = binomial, 
                    control = glmerControl(optimizer = "bobyqa", 
                                           optCtrl = list(maxfun = 100000)))
modelo_lme %>% summary()

# Previsões para o modelo GLMM
pred_lme <- predict(modelo_lme, type = "response")
# Converter previsões em binário
class_pred_lme <- ifelse(pred_lme > 0.5, 1, 0)
```


```{r}
library(pROC)
library(caret)

# Métricas para GEE
conf_matrix_gee <- confusionMatrix(factor(class_pred_gee), factor(dff$ideal))
roc_gee <- roc(dff$ideal, pred_gee)

# Métricas para GLMM
conf_matrix_lme <- confusionMatrix(factor(class_pred_lme), factor(dff$ideal))
roc_lme <- roc(dff$ideal, pred_lme)

# Imprimir resultados
cat("GEE Confusion Matrix:\n")
print(conf_matrix_gee)
cat("GEE AUC:", auc(roc_gee), "\n\n")

cat("GLMM Confusion Matrix:\n")
print(conf_matrix_lme)
cat("GLMM AUC:", auc(roc_lme), "\n")

```
```{r}
modelo_lme = modelo_b

summary_lme = modelo_lme %>% summary()
summary_lme = summary_lme$coefficients #%>% round(2)
summary_lme[,-4] = summary_lme[,-4] %>% round(2)
summary_lme[,4] = summary_lme[,4] %>% round(4)
summary_lme

ic = confint(modelo_lme, method = "Wald")
ic <- ic[-c(1), ]
ic

cbind(summary_lme, ic)
```
```{r}
df_filter <- df %>% filter(Momento == 'A') %>% filter(PEEP != '6') %>% 
  mutate(PEEP = factor(PEEP))

df_filter$PEEP %>% levels()

table(df_filter$PEEP)

table(df_filter$PEEP, df_filter$ideal)

```



```{r}
df_a <- df %>% filter(Momento == 'A') %>% filter(PEEP != '6') %>% mutate(PEEP = factor(PEEP))
#df_a
modelo_a <- glmer(ideal ~ PEEP + (1 | ind), data = df_a, family = binomial,
                  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
modelo_a %>% summary()
#

df_b <- df %>% filter(Momento == 'B') %>% filter(PEEP != '6') %>% mutate(PEEP = factor(PEEP))
#df_b
modelo_b <- glmer(ideal ~ PEEP + (1 | ind), data = df_b, family = binomial, 
                  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
#modelo_b %>% summary()
#

df_c <- df %>% filter(Momento == 'C') %>% filter(PEEP != '6') %>% mutate(PEEP = factor(PEEP))
#table(df_c$ideal)
modelo_c <- glmer(ideal ~ PEEP + (1 | ind), data = df_c, family = binomial, 
                  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
#modelo_c %>% summary()
#
```


```{r}

modelo_analisado = modelo_a
summary_lme = modelo_analisado %>% summary()
summary_lme = summary_lme$coefficients
ic = confint(modelo_analisado, method = "Wald")
ic <- ic[-c(1), ]
estimadores_a = cbind(summary_lme, ic)[-1,] %>% as.data.frame()
estimadores_a$momento = 'a'
estimadores_a[["Variable"]] = rownames(estimadores_a)
estimadores_a

#################################
modelo_analisado = modelo_b
summary_lme = modelo_analisado %>% summary()
summary_lme = summary_lme$coefficients
ic = confint(modelo_analisado, method = "Wald")
ic <- ic[-c(1), ]
estimadores_b = cbind(summary_lme, ic)[-1,] %>% as.data.frame()
estimadores_b$momento = 'b'
estimadores_b[["Variable"]] = rownames(estimadores_b)
estimadores_b

#################################
modelo_analisado = modelo_c
summary_lme = modelo_analisado %>% summary()
summary_lme = summary_lme$coefficients
ic = confint(modelo_analisado, method = "Wald")
ic <- ic[-c(1), ]
estimadores_c = cbind(summary_lme, ic)[-1,] %>% as.data.frame()
estimadores_c$momento = 'c'
estimadores_c[["Variable"]] = rownames(estimadores_c)
estimadores_c
##################################################################

estimadores = rbind(estimadores_a, estimadores_b, estimadores_c)
names(estimadores)[names(estimadores) == "Pr(>|z|)"] = "p_value"
names(estimadores)[names(estimadores) == "2.5 %"] = "IC_0"
names(estimadores)[names(estimadores) == "97.5 %"] = "IC_1"
estimadores = apply_retorne_p(estimadores, 'p_value')
rownames(estimadores) = 1:nrow(estimadores)

estimadores$estimador = NA
for (i in 1:nrow(estimadores)){ 
  estimadores$estimador[i] = paste0( rround(estimadores$Estimate[i],2), 
                                     ' (', rround(estimadores$IC_0[i],2), 
                                     ' to ', 
                                     rround(estimadores$IC_1[i],2), ')')
}

estimadores$Variable %>% table()
estimadores$Variable = factor(estimadores$Variable, labels=c('10','12','14','16','18','20'))
estimadores$Variable %>% as.character() %>% table()
estimadores

# legendas = estimadores %>%
#   group_by(Variable, momento) %>%
#   summarise(p_value = paste(p_value, collapse = '\n'), 
#             estimador = paste(estimador, collapse = '\n')) %>%
#   ungroup()
# legendas

estimadores = estimadores %>% filter(momento == 'a')
estimadores

```

```{r}
plot1 = ggplot(estimadores, aes(y = Variable, x = Estimate)) + #
  geom_point(shape = 18, size = 5, position = position_dodge(width = 0.5)) +  
  geom_errorbarh(aes(xmin = IC_0, xmax = IC_1), height = 0.25, position = position_dodge(width = 0.5)) +
  geom_vline(xintercept = 0, color = "tomato", linetype = "dashed", cex = 1, alpha = 0.5) +
  labs(title=' ', x="Estimators of Generalized Linear Mixed-Effects Model (95% CI)", y='PEEP') +
  theme_bw() +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = 0.5, size=12),
        panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black")) +
  theme_bw() + guides(color = FALSE)
  #scale_x_continuous(trans='log10') #+ geom_text(aes(label = pvalor))

table_base = ggplot(estimadores, aes(y=Variable)) +
  labs(y=NULL) + 
  theme_bw() +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())

tab1 = table_base +
  geom_text(aes(x = 1, label = p_value, fontface = "bold"), size = 4, position = position_dodge(width = 0.5)) + #, color = momento
  labs(title="P-valor", x=NULL)

tab2 = table_base + 
  labs(title = "space") +
  geom_text(aes(x = 1, label = estimador, fontface = "bold"), size = 4, position = position_dodge(width = 0.5)) + #, color = momento
  labs(title="Estimator", x=NULL)

lay =  matrix(c(1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid = grid.arrange(plot1, tab1, tab2, layout_matrix = lay)
ggsave("medida_efeito.png", grid, width = 25, height = 20, units = "cm", dpi = 300)

```





```{r Comparação par a par}
library(multcomp)

# Preparar contrastes para comparações par a par
contrasts_matrix <- contrMat(table(df_a$PEEP), "Tukey")

comp <- glht(modelo_a, linfct = mcp(PEEP = contrasts_matrix))
summary(comp)

plot(comp)
```

```{r}
#estimadores_c = tidy(summary(comp))

#################################
summary_lme = glht(modelo_a, linfct = mcp(PEEP = contrasts_matrix)) %>% summary()
ic = confint(summary_lme)
ic = ic$confint
summary_lme = summary_lme[["test"]][["pvalues"]]
estimadores_a = cbind(ic, summary_lme) %>% as.data.frame()
estimadores_a$Variable = rownames(estimadores_a)
estimadores_a$momento = 'a'
#################################
summary_lme = glht(modelo_b, linfct = mcp(PEEP = contrasts_matrix)) %>% summary()
ic = confint(summary_lme)
ic = ic$confint
summary_lme = summary_lme[["test"]][["pvalues"]]
estimadores_b = cbind(ic, summary_lme) %>% as.data.frame()
estimadores_b$Variable = rownames(estimadores_b)
estimadores_b$momento = 'b'
#################################
summary_lme = glht(modelo_c, linfct = mcp(PEEP = contrasts_matrix)) %>% summary()
ic = confint(summary_lme)
ic = ic$confint
summary_lme = summary_lme[["test"]][["pvalues"]]
estimadores_c = cbind(ic, summary_lme) %>% as.data.frame()
estimadores_c$Variable = rownames(estimadores_c)
estimadores_c$momento = 'c'
##################################################################
estimadores = rbind(estimadores_a, estimadores_b, estimadores_c)

rownames(estimadores) = 1:nrow(estimadores)
names(estimadores)[names(estimadores) == "summary_lme"] = "p_value"
names(estimadores)[names(estimadores) == "lwr"] = "IC_0"
names(estimadores)[names(estimadores) == "upr"] = "IC_1"
estimadores$estimador = NA
for (i in 1:nrow(estimadores)){ 
  estimadores$estimador[i] = paste0( rround(estimadores$Estimate[i],2), 
                                     ' (', rround(estimadores$IC_0[i],2), 
                                     ' to ', 
                                     rround(estimadores$IC_1[i],2), ')')
}
estimadores = apply_retorne_p(estimadores, 'p_value')


estimadores$Variable %>% factor() %>% levels()
ordem = c("10 - 8","12 - 8","14 - 8","16 - 8","18 - 8","20 - 8", #
          "12 - 10","14 - 10","16 - 10","18 - 10","20 - 10", #
          "14 - 12","16 - 12","18 - 12","20 - 12",#
          "16 - 14","18 - 14","20 - 14",#
          "18 - 16","20 - 16",#
          "20 - 18")
estimadores$Variable <- factor(estimadores$Variable, levels = ordem)
#estimadores$Variable = paste0("'", estimadores$Variable)
#estimadores %>% capture()

estimadores = estimadores %>% filter(momento == 'a')
estimadores

```

```{r}
plot1 = ggplot(estimadores, aes(y = Variable, x = Estimate)) + #, color = momento
  geom_point(shape = 18, size = 5, position = position_dodge(width = 0.5)) +  
  geom_errorbarh(aes(xmin = IC_0, xmax = IC_1), height = 0.25, position = position_dodge(width = 0.5)) +
  geom_vline(xintercept = 0, color = "tomato", linetype = "dashed", cex = 1, alpha = 0.5) +
  labs(title=' ', x="Estimators of Generalized Linear Mixed-Effects Model (95% CI)", y='PEEP') +
  theme_bw() +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = 0.5, size=12),
        panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black")) +
  theme_bw() + guides(color = FALSE)
  #scale_x_continuous(trans='log10') #+ geom_text(aes(label = pvalor))

table_base = ggplot(estimadores, aes(y=Variable)) +
  labs(y=NULL) + 
  theme_bw() +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())

tab1 = table_base +
  geom_text(aes(x = 1, label = p_value, fontface = "bold"), size = 4, position = position_dodge(width = 0.7)) + #, color = momento
  labs(title="P-valor", x=NULL)

tab2 = table_base + 
  labs(title = "space") +
  geom_text(aes(x = 1, label = estimador, fontface = "bold"), size = 4, position = position_dodge(width = 0.7)) + #, color = momento
  labs(title="Estimator", x=NULL)

lay =  matrix(c(1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid = grid.arrange(plot1, tab1, tab2, layout_matrix = lay)
ggsave("medida_efeito_par_a_par.png", grid, width = 25, height = 40, units = "cm", dpi = 300)
```




















































```{r}
dff = df %>% filter(Momento == 'A')
nrow(dff)

library(multcomp)
coluna = 'ideal'

glm_model = glm(dff[[coluna]] ~ PEEP, family = binomial, data = dff)
comp = glht(glm_model, linfct = mcp(PEEP = "Tukey"))

tabela = summary(comp)
tabela = tidy(summary(comp))

tabela$contrast = paste0("'",tabela$contrast)
tabela$term = NULL
tabela$null.value = NULL
tabela$estimate = round(tabela$estimate, 2)
tabela$std.error = round(tabela$std.error, 2)
tabela$statistic = round(tabela$statistic, 2)
tabela = apply_retorne_p(tabela, "adj.p.value")

tabela #%>% capture()

#confint(comp)
#tabela[["test"]][["pvalues"]]

```

```{r}

tabela = table(dff$ideal, dff$PEEP)
tabela = chisq.test(tabela)
tabela$residuals

```
```{r}
library(chisq.posthoc.test)

dff = df %>% filter(Momento == 'A')
tabela = table(dff$ideal, dff$PEEP)

chisq.posthoc.test(tabela)

```


```{r}
tabela = chisq.multcomp( table(dff$PEEP, dff$ideal), p.method = "none")
tabela
tabela = tabela$p.value %>% as.data.frame()
tabela

colunas_numericas <- sapply(tabela, is.numeric)
for (coluna in names(tabela)[colunas_numericas]) {
  tabela <- apply_retorne_p(tabela, coluna)
}
tabela

```

